# Generated by Django 4.1.4 on 2023-01-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_routes',
            name='rate',
        ),
        migrations.AddField(
            model_name='rout_detailes',
            name='rate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
