# Generated by Django 4.1.4 on 2023-01-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_1',
        ),
    ]
