# Generated by Django 4.1.4 on 2023-01-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
