# Generated by Django 4.1.4 on 2023-01-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_email_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='Password1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='Password2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
