# Generated by Django 4.1.4 on 2023-01-13 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_bus_booking_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingName', models.CharField(blank=True, help_text='Probably the surname of your party.', max_length=100)),
                ('PubName', models.CharField(blank=True, max_length=255)),
                ('PartySize', models.IntegerField(blank=True, default='1', help_text='Due to current government reulations this has a maximum value of 6.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('TableNo', models.IntegerField(blank=True, default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('Time', models.CharField(blank=True, default='09:00', help_text='Please select a time in 24hr clock format (HH:MM) from the drop down.', max_length=13)),
                ('Email', models.EmailField(help_text='Please provide email in case of cancellation.', max_length=254)),
                ('Day', models.CharField(blank=True, max_length=9)),
            ],
        ),
    ]
