# Generated by Django 4.1.4 on 2023-01-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.RenameField(
            model_name='bus_booking',
            old_name='name',
            new_name='place',
        ),
    ]
